name = "z-chat-relay"
main = "src/index.js"
compatibility_date = "2024-11-01"
account_id = "08d1a324e6d5775965f1c2887fd17014"
workers_dev = true

durable_objects.bindings = [
  { name = "RELAY", class_name = "Relay" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Relay"]
